apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: awesomenamespace/awesomeapp
deploy:
  helm:
    flags:
      global: ["--tiller-namespace=helm-test"]
    releases:
      - name: awesomeapp
        namespace: helm-test
        skipBuildDependencies: true
        chartPath: awesomeapp
        values:
          image.repository: awesomenamespace/awesomeapp
portForward:
  - resourceType: deployment
    resourceName: awesomeapp-php
    namespace: helm-test
    port: 80
    localPort: 8080
